import type { NextRequest } from "next/server";
import { fetchCaptions } from "@/lib/captions";

// Fetches YouTube captions SERVER-SIDE on Vercel (different IP than the blocked
// Render backend, and same-origin to the browser so no CORS). Uses a cascade of
// strategies (see lib/captions.ts) so that auto-generated captions are found
// even when the simple npm scrape 502s. The client then renders these segments.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const LOG = "[transcript-route]";

export async function GET(request: NextRequest) {
  const videoId = request.nextUrl.searchParams.get("videoId")?.trim();
  const lang = request.nextUrl.searchParams.get("lang")?.trim() || "en";
  console.log(`${LOG} ← request received`, {
    videoId,
    lang,
    url: request.nextUrl.pathname + request.nextUrl.search,
  });

  if (!videoId) {
    console.warn(`${LOG} ✗ rejected: missing videoId`);
    return Response.json({ error: "videoId is required." }, { status: 400 });
  }

  const startedAt = Date.now();
  try {
    const result = await fetchCaptions(videoId, lang);

    console.log(`${LOG} → responding 200`, {
      videoId,
      strategy: result.strategy,
      languageCode: result.languageCode,
      autoGenerated: result.isAutoGenerated,
      segmentCount: result.segments.length,
      tookMs: Date.now() - startedAt,
      firstSegment: result.segments[0] ?? null,
      lastSegment: result.segments.at(-1) ?? null,
    });

    return Response.json({
      video_id: videoId,
      source_lang: result.languageCode,
      is_auto_generated: result.isAutoGenerated,
      strategy: result.strategy,
      segments: result.segments,
    });
  } catch (error) {
    // We only land here if EVERY strategy failed — the message lists what each
    // one reported so the failure is debuggable from the response/logs.
    const message = error instanceof Error ? error.message : "Transcript unavailable.";
    console.error(`${LOG} ✗ all strategies failed`, {
      videoId,
      lang,
      tookMs: Date.now() - startedAt,
      message,
    });
    return Response.json(
      { error: message, videoId, detail: "AllStrategiesFailed" },
      { status: 502 },
    );
  }
}
